name: Build and publish new version

on:
  push:
    branches:
      - main
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Setup git user
        shell: bash
        run: git config user.email "bot@weichwarenprojekt.de" && git config user.name "Weichwarenbot 🚀"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - name: Version
        shell: bash
        run: npx wersion
        # push the changes
      - run: git push --follow-tags
      - name: Test
        run: npm run coverage
      - name: Build
        run: npm run build
      - name: Publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
        run: npm publish
